[server]
address = "127.0.0.1"
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 2
fileWatcherType = "none"

[browser]
serverAddress = "127.0.0.1"
gatherUsageStats = false

[client]
toolbarMode = "minimal"
