[server]
address = "127.0.0.1"
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 2
fileWatcherType = "none"

[browser]
serverAddress = "127.0.0.1"
gatherUsageStats = false

[client]
toolbarMode = "minimal"
disableDataExport = true

[theme]
base = "light"
primaryColor = "#52635c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f4"
textColor = "#292524"
font = "sans serif"
